name: Crypt-DSA
version: 0.13
abstract: DSA signatures and key generation
author: Benjamin Trott <cpan@stupidfool.org>
license: perl
distribution_type: module
requires:
  Math::BigInt: 1.60
  Digest::SHA1: 0
recommends:
  Convert::PEM: 0.07
  Data::Buffer: 0.01
no_index:
  directory:
    - t
    - inc
generated_by: Module::Install version 0.36
